export const data = [
  {
    id: 1,
    img: "https://i.postimg.cc/sXLn3H0p/367027497-773062894828603-7949697918615314726-n.png",
    name: "Pero Andrés Guerrero",
    country: "Ecuador",
    bandera: "https://i.postimg.cc/25rTvWFd/ecuador.png",
    about: "Ingeniero ambiental, amante de las montañas, las carreras de trail, las películas y los perros",
    profesion: "Data Science",
    grito: "Por Narnia",
  },
  {
    id: 2,
    img: "https://i.postimg.cc/t4GM1fRk/25182049-10213231827644725-8004914208025687205-o.jpg",
    name: "Daniel Contreras",
    country: "Chile",
    bandera: "https://i.postimg.cc/HkG6YRrh/chille.png",
    about:
      "Desde pequeño tuve afinidad con los computadores y la programación, a los 8 años hice mi primera web básica usando bloc de notas y algún que otro juego en RPGMaker (programaba sin saberlo). Entre a estudiar Ingenieria Civil plan común con el objetivo de elegir la especialidad de Informática, sin embargo, por cosas de la vida, terminé eligiendo la especialidad de Electricidad (grave error). Me titulé y trabajé algunos años en esto, pero nunca me terminó de gustar. Desde hace años me han apasionado las redes neuronales y la inteligencia artificial y ahora que este campo esta tomando fuerza, finalmente decidí cambiar de rubro hacia mi verdadera vocación.",
    profesion: "Data Science",
    grito: "Hola",
  },
  {
    id: 3,
    img: "https://i.postimg.cc/d04HxV2N/DSC-0515.jpg",
    name: "Aracely Cruz Del ángel",
    country: "México",
    bandera: "https://i.postimg.cc/d10BNKfL/mexico.png",
    about: "Desarrolladora web, team café, me encantan los gatos",
    profesion: "Web Developer",
    grito: "Miau",
  },
  {
    id: 4,
    img: "https://i.postimg.cc/bJrCcfLy/yo.png",
    name: "Josué Lopez",
    country: "Venezuela",
    bandera: "https://i.postimg.cc/XvLLgvQR/venezuela.png",
    about: "Emprendedor amante de la tecnologia, Filosofia y baile =)",
    profesion: "Web Developer",
    grito: "Hakuna Matata",
  },
];
